import "./globals.css";

import Footer from "@/components/shared/Footer";
import TopBar from "@/components/shared/TopBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <TopBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
