// Every short "what is this" tip in the PMS, by page (owner, 2026-10-03:
// "add these short tooltips (with the i icon) to every subsection,
// component, heading, button, field ... Then later, I can tell you where to
// cut them off"). Each is shown by an (i) - <Tip id> in components/pms/Tip.jsx
// - and deleting an entry here removes that (i) wherever it is used. Never on
// buttons or tabs (owner, 2026-10-05). Abbreviations (ADR, OTA, ...) have
// their own list in components/pms/InfoTip.jsx.
//
// Ids are "page.section.thing". Plain words, one or two sentences: what it is.
export const TIPS = {
  // ---- Pages
  "overview.page": "This branch today: rooms occupied and free, who is arriving and leaving, open alerts and the latest bookings.",
  "rooms.page": "Each room type's rooms, prices and capacity, and every room's status - in use, free, out of order, set aside or complimentary.",
  "roomChart.page": "Every room across the days ahead, with the stay in it each night - to see at a glance what is booked and what is free.",
  "reservations.page": "Every booking at this branch - website, walk-in and OTA - to confirm, change dates, take deposits, cancel or export.",
  "guests.page": "Everyone who has stayed or booked: contact details, VIP or blacklisted, notes and their stays.",
  "folios.page": "Each stay's bill: charges, payments, credit and refunds. A folio opens when a booking is confirmed.",
  "fnbSales.page": "Food and Beverage (F&B) sales - the restaurant and bar: to guests on their folio, and to people who aren't staying.",
  "laundry.page": "Laundry work: for guests, charged to their folio, and for people who aren't staying, paid on the spot.",
  "checkIns.page": "Today's arrivals to check in, a guest walking in without a booking, and booking a later stay at the desk.",
  "checkOuts.page": "Guests due to leave on the chosen day: settle their bill and check them out.",
  "inHouse.page": "Guests staying right now: extend a stay, change room or room type, add notes or check out early.",
  "reports.page": "The branch's figures for a day or a range of days, and the daily reports, each exportable to Excel.",
  "nightAudit.page": "Closes a business day (6am to 6am): posts the night's room charges and records the day's totals.",
  "alerts.page": "Things that need attention now: missed check-ins, unconfirmed holds, overdue check-outs and balances, and credit owed to guests.",
  "otaPayments.page": "Money owed by Online Travel Agencies (OTAs) such as Booking.com for nights they sold, and recording it when it arrives.",
  "auditTrail.page": "Who did what and when, in plain words - every change made in the PMS, newest first.",
  "menu.page": "The food, drink and laundry price lists, and drink stock.",
  "account.page": "Your own sign-in: change your password.",
  "help.page": "How each page works, and the day's workflow from check-in to night audit.",
  "critical.page": "Every room out of order across all branches, longest out first, live.",
  "decisionSupport.page": "What to fix first across the branches, worked out from their own records, with a suggestion for each.",
  "metrics.page": "Group-wide figures, branch by branch: rooms and revenue, money and credit, guests, F&B and stock, operations and staff.",
  "staffAccounts.page": "Every staff sign-in at every branch: add, change roles, reset passwords, or disable.",
  "guestSales.page": "Food and drink sold to guests staying here, charged to their folio.",
  "nonGuestSales.page": "Food and drink sold to people who aren't staying, paid on the spot or kept on an open tab.",
  "laundryGuestSales.page": "Laundry done for guests staying here, charged to their folio.",
  "laundryNonGuestSales.page": "Laundry done for people who aren't staying, paid on the spot.",
  // ---- Check-Ins
  "checkIns.arrivals.date": "The arrival date to list. Check-in opens on each guest's arrival day.",
  "checkIns.arrivals.guest": "Who the booking is for, with any VIP or Blacklisted tag and whether their confirmation email arrived.",
  "checkIns.arrivals.roomType": "The room type booked.",
  "checkIns.arrivals.checkOut": "The day the guest is booked to leave.",
  "checkIns.arrivals.status": "Confirmed: paid and ready to check in. Hold: awaiting payment - confirm it in Reservations first.",
  "checkIns.arrivals.actions": "Check In: assign the room numbers, note any OTA-paid nights and check the guest in. Open once the booking is confirmed, on its arrival day.",
  "checkIns.walkIn.checkOut": "The day the guest leaves. Before 6am a stay counts from the night before, so today is allowed; from 6am the earliest is tomorrow.",
  "checkIns.walkIn.rooms": "How many rooms this guest needs, all of the same type.",
  "checkIns.walkIn.roomType": "The room type to book. Only types with enough rooms free for these dates are listed, with their nightly price.",
  "checkIns.walkIn.roomRate": "The price per room per night. It starts at the room type's rate; change it to agree a different price. The stay's total updates as you type.",
  "checkIns.walkIn.discount": "Takes a fixed amount or a percentage off the room type's own rate, and puts the result in Room Rate.",
  "checkIns.walkIn.withoutBreakfast": "Tick if breakfast isn't wanted: its price is left off every night of the stay.",
  "checkIns.walkIn.complementary": "A free stay: no room charge is posted, and the room shows as complimentary on Rooms and the Room Chart.",
  "checkIns.walkIn.knownNames": "Other names this phone number has been booked under. Pick one to fill in the name.",
  "checkIns.walkIn.firstName": "The guest's first name. Typing it shows matching past guests to pick from.",
  "checkIns.walkIn.lastName": "The guest's last name.",
  "checkIns.walkIn.phone": "The guest's phone number - how a returning guest is recognised. Their VIP or Blacklisted tag shows as you type.",
  "checkIns.walkIn.email": "Optional. Saved on the guest's profile; an address that can't receive mail is refused.",
  "checkIns.walkIn.roomNumbers": "The room the guest will sleep in (one per room booked). Only rooms free for the whole stay are offered.",
  "checkIns.walkIn.payment": "Money the guest pays now, if any - recorded on their folio at check-in. Leave the amount blank to take it later from the folio.",
  "checkIns.walkIn.paymentTax": "Optional. Adds tax to the bill when the payment is recorded: a fixed amount, or a percentage of the stay total.",
  "checkIns.walkIn.paymentDiscount": "Optional. Takes an amount off the bill when the payment is recorded: a fixed amount, or a percentage of the stay total.",
  "checkIns.walkIn.receipt": "The number on the paper receipt, if one was written, to match the payment to it.",
  "checkIns.walkIn.remarks": "A note kept with the payment - who paid, or how.",
  "checkIns.ota.on": "Tick when an online travel agency (Booking.com, Expedia...) is paying for some of the nights. Nights outside its dates stay on the guest's own bill.",
  "checkIns.ota.from": "The first night the OTA pays for.",
  "checkIns.ota.until": "The day the OTA's nights end, like a check-out date - at least one night after From.",
  "checkIns.ota.breakfast": "Tick if the OTA's rate includes breakfast for those nights.",
  "checkIns.ota.amount": "What the OTA will pay for those nights. Leave it blank to use the room's own rate for them.",
  "checkIns.checkIn.roomType": "The room type booked.",
  "checkIns.checkIn.roomsBooked": "How many rooms the booking is for; each needs a room number.",
  "checkIns.checkIn.rooms": "The room number for each room booked. Only rooms free for the whole stay are offered.",
  "checkIns.future.heading": "Book a later stay for a guest at the desk. A room number is needed - it holds that room for the dates.",
  "checkIns.future.firstName": "The guest's first name. Typing it shows matching past guests to pick from.",
  "checkIns.future.lastName": "The guest's last name.",
  "checkIns.future.phone": "The guest's phone number - how a returning guest is recognised.",
  "checkIns.future.email": "Optional. Saved on the guest's profile; an address that can't receive mail is refused.",
  "checkIns.future.checkIn": "The night the guest arrives - tomorrow or later. A guest arriving today is a Walk-In.",
  "checkIns.future.checkOut": "The day the guest leaves - at least one night after check-in. It moves along by itself if check-in passes it.",
  "checkIns.future.rooms": "How many rooms, all of the same type.",
  "checkIns.future.roomType": "Room types with enough rooms free for these dates, with their nightly price.",
  "checkIns.future.roomNumbers": "The room to hold for the stay (one per room booked). It can be changed any time before the guest arrives.",
  // ---- Overview
  "overview.allClear": "Nothing on the Alerts page needs attention right now.",
  "overview.houseStatus": "Each room type tonight: its rooms, how many are occupied or held, and how many are free.",
  "overview.house.roomType": "The room type.",
  "overview.house.total": "How many rooms of this type the branch has.",
  "overview.house.occupied": "Rooms with a guest in them, or held for a booking.",
  "overview.house.available": "Rooms of this type still free to sell tonight.",
  "overview.house.occupancy": "How full this room type is: occupied or held, out of its rooms.",
  "overview.recent": "The latest bookings at this branch, newest first.",
  "overview.recent.guest": "Who the booking is for, and its booking reference.",
  "overview.recent.roomType": "The room type booked.",
  "overview.recent.checkIn": "The night the stay starts.",
  "overview.recent.checkOut": "The day the guest leaves.",
  "overview.recent.status": "Hold: awaiting payment. Confirmed: paid, not arrived yet. Active: checked in. Completed: checked out. Cancelled.",
  // ---- Check-Outs
  "checkOuts.date": "The departure date to list: guests booked to leave that day.",
  "checkOuts.guest": "The guest due to leave, with any VIP or Blacklisted tag.",
  "checkOuts.roomType": "The room type they stayed in.",
  "checkOuts.checkedIn": "When they checked in.",
  "checkOuts.actions": "Check Out: see the folio balance and check the guest out. Early Departure: for a guest leaving before their booked date - set the check-out to today first, so the bill matches the nights slept.",
  "checkOuts.balance": "What the guest still owes on this stay's bill. Red: money owed. Green: settled.",
  // ---- In-House
  "inHouse.guest": "The guest staying, with any VIP or Blacklisted tag.",
  "inHouse.rooms": "The room numbers they are in.",
  "inHouse.checkedIn": "When they checked in.",
  "inHouse.expectedCheckOut": "The day they are booked to leave. Overdue: past noon on that day and still here.",
  "inHouse.actions": "View: the stay's details - balance, notes, rooms, change of room type, extending, and checking out.",
  "inHouse.detail.checkedIn": "When the guest checked in.",
  "inHouse.detail.expectedCheckOut": "The day they are booked to leave.",
  "inHouse.balance": "What the guest still owes on this stay's bill. Red: money owed. Green: settled.",
  "inHouse.notes": "Notes for this stay, e.g. \"Arriving late\". They show in the Manifest report.",
  "inHouse.roomAssignments": "The room numbers the guest is in. Change one to move the guest to another room of the same type.",
  "inHouse.changeRoomType": "Move the guest to a different room type. Nights already billed keep their rate; nights from here on bill at the new type's rate.",
  "inHouse.extendStay": "Pick a later check-out date to keep the guest longer. The extra nights are billed at the stay's own rate.",
  // ---- Rooms
  "rooms.col.roomType": "The room type.",
  "rooms.col.price": "The room type's price per night, and the breakfast price added per night when breakfast is included. Managers can change them here and press Update.",
  "rooms.col.actions": "View: the room type's details, its rooms and their status, prices and capacity.",
  "rooms.add.name": "What the room type is called, e.g. Deluxe Suite. Guests see it on the website.",
  "rooms.add.summary": "A short description of the room type for the website.",
  "rooms.add.amenities": "What the room has, separated by commas, e.g. Free WiFi, AC, King Size Bed.",
  "rooms.add.adults": "How many adults one room sleeps.",
  "rooms.add.children": "How many children one room sleeps.",
  "rooms.add.currency": "The currency sign shown with the price, e.g. ₦.",
  "rooms.add.rate": "The price per room per night, without breakfast.",
  "rooms.add.breakfast": "The breakfast price added per night when breakfast is included.",
  "rooms.add.capacity": "How many rooms of this type the hotel has.",
  "rooms.view.available": "Rooms of this type free right now.",
  "rooms.view.adults": "How many adults one room sleeps.",
  "rooms.view.children": "How many children one room sleeps.",
  "rooms.view.details": "The description, amenities and capacity guests see on the website.",
  "rooms.view.summary": "A short description of the room type for the website.",
  "rooms.view.amenities": "What the room has, separated by commas.",
  "rooms.view.adultsField": "How many adults one room sleeps.",
  "rooms.view.childrenField": "How many children one room sleeps.",
  "rooms.view.physical": "Every room of this type and its status: Available, Out of Order (needs fixing, not sold), Complementary (free to its guest) or Reserved (set aside for a manager). Occupied shows by itself while a guest is in.",
  "rooms.view.basePrice": "The price per room per night, without breakfast. New bookings use it; existing ones keep their price.",
  "rooms.view.breakfast": "The breakfast price added per night when breakfast is included.",
  "rooms.view.capacity": "How many rooms of this type the hotel has. Fewer removes rooms - refused if any of them are in use or booked.",
  // ---- Room Chart
  "roomChart.date": "Jump to any date: it becomes the first day shown.",
  "roomChart.legend": "What each bar's colour means. Each bar is a stay across the nights it covers; press one to see its booking.",
  // ---- Reservations
  "reservations.filter.status": "Hold: booked, not yet paid. Confirmed: paid, not yet arrived. Active: checked in. Completed: checked out. Cancelled: called off.",
  "reservations.filter.source": "Type a source, e.g. website, walk-in or ota, to list only those bookings.",
  "reservations.filter.channel": "Type a booking channel exactly as it was recorded to list only those bookings.",
  "reservations.filter.dates": "Lists bookings arriving between these two dates. Both are needed.",
  "reservations.filter.noShows": "Lists only bookings marked as no-shows.",
  "reservations.col.guest": "The guest the booking is for, with any VIP or Blacklisted tag.",
  "reservations.col.checkIn": "The day the guest is booked to arrive.",
  "reservations.col.checkOut": "The day the guest is booked to leave.",
  "reservations.col.status": "Where the booking stands: hold, confirmed, active, completed or cancelled. No-Show: the guest never arrived. Hold Expired: a website booking not paid within 2 hours, so its room was released.",
  "reservations.col.source": "Where the booking came from, e.g. the website, a walk-in or an OTA.",
  "reservations.col.actions": "View: the booking's details, dates, credit, rooms and actions. Cancel: calls off a booking that has not checked in.",
  "reservations.info.checkIn": "The day the guest is booked to arrive.",
  "reservations.info.checkOut": "The day the guest is booked to leave.",
  "reservations.info.rooms": "How many rooms this booking takes.",
  "reservations.info.source": "Where the booking came from.",
  "reservations.stayDates": "Change the arrival or departure date before the guest arrives. The price follows the new number of nights at this booking's own rate.",
  "reservations.checkInDate": "The day the guest arrives. Today at the earliest.",
  "reservations.checkOutDate": "The day the guest leaves. At least one night after the check-in date.",
  "reservations.details": "The guest's requests and the stay's price.",
  "reservations.specialRequests": "Anything the guest asked for, e.g. a late arrival or an extra bed.",
  "reservations.totalRate": "The price of the whole stay. Editable until the booking is confirmed; after that, correct it on the folio.",
  "reservations.totalCredit": "The total of the reservation credit recorded below. It fills in by itself.",
  "reservations.discount": "Money off the stay's price, as a fixed amount or a percentage. Only before the booking is confirmed.",
  "reservations.folio": "This booking's bill, its number and what is still owed. It opens by itself when the booking is confirmed.",
  "reservations.previousCredit": "Money this guest paid on another booking that was never used. Apply puts it towards this stay's bill.",
  "reservations.credit": "Money paid ahead for this booking. Apply: settles what the stay owes from it. Transfer: moves it to another booking. Refund: pays it back to the guest. Transfer and Refund: receptionists and managers.",
  "reservations.newDeposit": "Record money the guest paid ahead for this booking, split across payment methods if needed.",
  "reservations.receiptNumber": "The number on the paper receipt given to the guest.",
  "reservations.remarks": "Anything worth noting about this payment.",
  "reservations.roomAssignments": "The room numbers this booking gets. Change one to move the guest to another room of the same type.",
  "reservations.changeRoomType": "Move the booking to a different room type. Nights already billed keep their rate; nights from here on bill at the new type's rate.",
  "reservations.extendStay": "Pick a later check-out date to keep the guest longer. The extra nights are billed at the stay's own rate.",
  "reservations.cancelReason": "Why the booking is being called off. It is kept with the booking.",
  "reservations.export.start": "The first day of bookings to include, by the date they were made.",
  "reservations.export.end": "The last day of bookings to include, by the date they were made.",
  "reservations.export.status": "Which bookings to include: active (checked in), confirmed (paid, not yet arrived), or both.",
  // ---- Guests
  "guests.search": "Type part of a name, or a full email address or phone number.",
  "guests.filter.status": "All guests, only the blacklisted, or only VIPs.",
  "guests.col.name": "The guest's name. Owing: money they still owe across their stays.",
  "guests.col.email": "The guest's email address.",
  "guests.col.phone": "The guest's phone number. It is what identifies a guest: one number, one profile.",
  "guests.col.status": "The guest's tags: VIP or Blacklisted.",
  "guests.col.stays": "How many stays the guest has completed (checked out).",
  "guests.col.actions": "View: the guest's details, status, notes and bookings.",
  "guests.knownNames": "Other names this phone number has booked under. Pick one to fill in the name fields.",
  "guests.firstName": "The guest's first name.",
  "guests.lastName": "The guest's last name.",
  "guests.email": "The guest's email address, for booking emails.",
  "guests.phone": "The country code and number. One number is one guest, so it matches a returning guest to their profile.",
  "guests.address": "The guest's street address.",
  "guests.city": "The guest's city.",
  "guests.country": "The guest's country.",
  "guests.status": "VIP: given extra care. Blacklisted: staff are warned not to host them; managers only. Both show as tags beside the guest's name on every screen.",
  "guests.blacklistReason": "Why the guest is blacklisted. Staff see it with the tag.",
  "guests.notes": "Notes about the guest that last across stays, e.g. a food allergy. Press × to delete one.",
  "guests.reservations": "Every booking this guest has made. Press an active or completed one to open its folio.",
  "guests.create.firstName": "The guest's first name. Required.",
  "guests.create.lastName": "The guest's last name. Required.",
  "guests.create.email": "The guest's email address, for booking emails.",
  "guests.create.phone": "The country code and number. Required: it is what identifies the guest.",
  "guests.create.status": "VIP: given extra care. It shows as a tag beside the guest's name on every screen.",
  "guests.create.company": "The company the guest works for or is staying through, if any.",
  // ---- Folios
  "folios.statusFilter": "Show only open folios (still in use) or closed ones (settled and finished).",
  "folios.col.guest": "The guest the folio is for, with any VIP or Blacklisted tag.",
  "folios.col.number": "The folio's own number, e.g. FOL-D7931B.",
  "folios.col.guestStatus": "For a folio still owed money. Still In-House: the guest hasn't checked out (Guest Ledger). City Ledger: the guest has left without paying it all.",
  "folios.col.checkOut": "The day the guest was booked to leave.",
  "folios.col.total": "Everything charged to the folio.",
  "folios.col.paid": "Everything paid towards it, including reservation credit.",
  "folios.col.balance": "What is still owed. Red: money owed. Green: credit the hotel holds for the guest.",
  "folios.col.status": "Open: still taking charges and payments. Closed: settled and finished.",
  "folios.col.actions": "View: the folio's charges, payments, credit and refunds.",
  "folios.sum.guest": "The guest the folio is for.",
  "folios.sum.checkIn": "When the guest checked in, to the minute - or the day they are expected.",
  "folios.sum.checkOut": "When the guest checked out, to the minute - or the day they are expected to. In red: they left before their booked date, so any nights they paid for and didn't stay show as credit.",
  "folios.sum.charged": "Everything charged to the folio.",
  "folios.sum.paid": "Everything paid towards it, including reservation credit.",
  "folios.sum.balance": "What the guest still owes. Settled: nothing owed.",
  "folios.otaAwaiting": "What an OTA still owes for the nights it is paying for. Never collect it from the guest.",
  "folios.guestToPay": "What the guest owes once the OTA's share is set aside.",
  "folios.ota.form": "The nights the OTA pays for and the amount it will send.",
  "folios.ota.from": "The first night the OTA pays for.",
  "folios.ota.until": "The day the OTA's nights end. The last night it pays for is the night before.",
  "folios.ota.breakfast": "Tick if the OTA's price includes breakfast for those nights.",
  "folios.ota.amount": "What the OTA will send for those nights. Filled in from the room rate; change it to match the OTA's own figure.",
  "folios.previousCredit": "Money this guest paid on another stay that was never used. Apply puts it towards this folio.",
  "folios.creditDue": "The guest has paid more than they owe. Refund it below, or leave it for a later charge.",
  "folios.reservationCredit": "Money paid ahead for this stay, and what became of it. Transfer: moves what's left to another folio. Refund: pays it back to the guest. Both: receptionists and managers.",
  "folios.charges": "Everything charged to the stay, night by night, with whether each charge is paid. A manager or the accountant can click a line to open it in the Audit Trail: who posted it, and when.",
  "folios.addCharge": "Post a charge to this folio by hand. Night charges post by themselves at night audit.",
  "folios.chargeType": "Room Charge, Penalty, Adjustment (a negative amount corrects an earlier charge) or Correction (fixes the accommodation charge without counting as an extra night).",
  "folios.amount": "The charge before tax and discount. Negative for an adjustment that takes money off.",
  "folios.tax": "Tax added to this charge, as a fixed amount or a percentage of it.",
  "folios.discount": "Money off this charge, as a fixed amount or a percentage of it.",
  "folios.description": "What the charge is for. It shows on the folio and the receipt.",
  "folios.chargeRemarks": "Anything worth noting about this charge.",
  "folios.payments": "Every payment and refund on this folio. Press the copy icon to copy a reference. A manager or the accountant can click a line to open it in the Audit Trail: who posted it, and when.",
  "folios.recordPayment": "Record money the guest has paid, split across payment methods if needed.",
  "folios.paymentTax": "Tax to add to the balance before this payment. It posts as its own line.",
  "folios.paymentDiscount": "Money off the balance before this payment. It posts as its own line.",
  "folios.paymentReceipt": "The number on the paper receipt given to the guest.",
  "folios.paymentRemarks": "Anything worth noting about this payment.",
  "folios.refund": "Pay back credit the guest holds on this folio. Receptionists and managers.",
  "folios.refundAmount": "How much to pay back, up to the credit on the folio.",
  "folios.refundMethod": "How the money goes back to the guest.",
  "folios.refundReceipt": "The number on the paper receipt for the refund.",
  "folios.refundRemarks": "Anything worth noting about this refund.",
  // ---- Shared parts
  "order.kind": "Food or drink: decides which menu the item comes from.",
  "order.item": "The menu item, with its price.",
  "order.quantity": "How many of the item.",
  "order.complementary": "Free of charge to the guest: the line is recorded but costs nothing.",
  "order.forManager": "For the manager's own use: recorded under the manager, free of charge.",
  "split.amount": "How much was paid by this method.",
  "split.method": "How it was paid: cash, card, transfer, POS or online.",
  "transactionReceipt.reference": "The payment's own reference. Search for it on Folios to find the payment again.",
  "refundCredit.paidOutBy": "How the money left the hotel: cash from the drawer, a transfer and so on.",
  "credits.unclaimed": "Money left over when a customer paid more than their bill. Apply it on the bill it should go to, or refund it.",
  "credits.customer": "Who paid the extra.",
  "credits.from": "The bill the overpayment came off.",
  "credits.type": "F&B or laundry.",
  "credits.dateTime": "When the overpayment was made.",
  "credits.amount": "How much is left to claim.",
  "credits.reference": "The credit's own reference.",
  "credits.actions": "Refund: pays the credit back. F&B credit by waitrons, laundry credit by receptionists.",
  "folioModal.balance": "What the guest still owes. Credit: they have paid more than they owe. Settled: nothing owed.",
  "folioModal.charged": "Everything charged to the guest's folio for the stay.",
  "folioModal.paid": "Everything paid towards it.",
  "folioModal.charges": "Every charge on the guest's folio, with whether each is paid.",
  "folioModal.recordPayment": "Record money the guest has paid towards their folio.",
  "folioModal.receipt": "The number on the paper receipt. Leave it blank and the system makes one.",
  "folioModal.notes": "Anything worth noting about this payment.",
  // ---- F&B Sales
  "guestSales.newOrder": "Post food and drink to an in-house guest's folio, then print the receipt.",
  "guestSales.guest": "The in-house guest the order is for, by room.",
  "guestSales.billNo": "The number on the paper bill. Leave it blank and the system makes one. One number covers the whole order.",
  "guestSales.total": "The order's total, service charge included. Complementary lines cost nothing.",
  "guestSales.col.guest": "The guest, with any VIP or Blacklisted tag.",
  "guestSales.col.room": "The guest's room.",
  "guestSales.col.folio": "The guest's folio number.",
  "guestSales.col.dateTime": "When the guest's folio was opened.",
  "guestSales.col.status": "Owing: the folio has money still due. Paid: settled.",
  "guestSales.col.actions": "View / Pay: the folio's charges, and a payment form.",
  "guestSales.col.checkedOut": "When the guest checked out.",
  "guestSales.col.balance": "What the guest still owes.",
  "nonGuestSales.newOrder": "Ring up food and drink for someone not staying. Pay now or later; the bill closes by itself once settled.",
  "nonGuestSales.name": "Not needed. Add it if the bill may stay unpaid a while, so it can be traced.",
  "nonGuestSales.phone": "Not needed. Add it if the bill may stay unpaid a while.",
  "nonGuestSales.billNo": "The number on the paper bill. Leave it blank and the system makes one. One number covers the whole order.",
  "nonGuestSales.total": "The order's total, service charge included. Complementary and manager lines cost nothing.",
  "nonGuestSales.col.guest": "The customer's name, or the bill number when no name was given.",
  "nonGuestSales.col.folio": "The bill's own folio number.",
  "nonGuestSales.col.dateTime": "When the bill was opened.",
  "nonGuestSales.col.total": "Everything on the bill.",
  "nonGuestSales.col.paid": "Everything paid towards it.",
  "nonGuestSales.col.balance": "What is still owed.",
  "nonGuestSales.col.status": "Owing: money still due. Paid: settled. PB: settled with credit from an earlier overpayment.",
  "nonGuestSales.col.actions": "View: the bill's items and payments, and forms to add to either.",
  "nonGuestSales.sum.charged": "Everything on the bill.",
  "nonGuestSales.sum.paid": "Everything paid towards it.",
  "nonGuestSales.sum.balance": "What is still owed. Settled: nothing owed.",
  "nonGuestSales.guestInfo": "The customer's name and phone, if the bill needs tracing later: an unpaid balance or a credit. Can be added any time.",
  "nonGuestSales.guestInfo.name": "The customer's name.",
  "nonGuestSales.guestInfo.phone": "The customer's phone number.",
  "nonGuestSales.charges": "Everything on the bill, with whether each item is paid.",
  "nonGuestSales.addCharge": "Add another item to this bill.",
  "nonGuestSales.kind": "Food or drink: decides which menu the item comes from.",
  "nonGuestSales.item": "The menu item, with its price.",
  "nonGuestSales.quantity": "How many of the item.",
  "nonGuestSales.itemBillNo": "The number on the paper bill for this item. Leave it blank and the system makes one.",
  "nonGuestSales.complementary": "Free of charge: the item is recorded but costs nothing.",
  "nonGuestSales.forManager": "For the manager's own use: recorded under the manager, free of charge.",
  "nonGuestSales.payments": "Every payment made on this bill.",
  "nonGuestSales.recordPayment": "Record money paid towards the bill. Anything paid over the balance is kept on file as credit.",
  "nonGuestSales.receipt": "The number on the paper receipt.",
  "nonGuestSales.remarks": "Anything worth noting about this payment.",
  "nonGuestSales.creditOnFile": "Money this customer overpaid on an earlier bill. Apply Credit puts it towards this one.",
  // ---- Laundry
  "laundryGuest.new": "Post a guest's laundry to their room's folio. It is settled with the rest of the stay.",
  "laundryGuest.guest": "The in-house guest the laundry is for, by room.",
  "laundryGuest.billNo": "The number on the paper bill. Leave it blank and the system makes one.",
  "laundry.clothes": "The garment, e.g. shirt or trousers. Each has its own price.",
  "laundry.type": "Wash & Iron, or Ironing Only. Each is priced on its own.",
  "laundry.count": "How many of the garment.",
  "laundryGuest.total": "The bill's total.",
  "laundryGuest.col.guest": "The guest, with any VIP or Blacklisted tag.",
  "laundryGuest.col.room": "The guest's room.",
  "laundryGuest.col.folio": "The guest's folio number.",
  "laundryGuest.col.dateTime": "When the guest's folio was opened.",
  "laundryGuest.col.status": "Owing: the folio has money still due. Paid: settled.",
  "laundryGuest.col.actions": "View / Pay: the folio's charges, and a payment form.",
  "laundrySales.new": "Record laundry for someone not staying. Pay now or later.",
  "laundrySales.name": "Not needed. Add it if the bill may stay unpaid a while, so it can be traced.",
  "laundrySales.phone": "Not needed. Add it if the bill may stay unpaid a while.",
  "laundrySales.billNo": "The number on the paper bill. Leave it blank and the system makes one.",
  "laundrySales.total": "The bill's total.",
  "laundrySales.folios": "Every laundry bill for customers not staying.",
  "laundrySales.col.customer": "The customer's name, or the bill number when no name was given.",
  "laundrySales.col.folio": "The bill's own folio number.",
  "laundrySales.col.dateTime": "When the bill was opened.",
  "laundrySales.col.total": "Everything on the bill.",
  "laundrySales.col.paid": "Everything paid towards it.",
  "laundrySales.col.balance": "What is still owed.",
  "laundrySales.col.status": "Owing: money still due. Paid: settled. PB: settled with credit from an earlier overpayment.",
  "laundrySales.col.actions": "View / Pay: the bill's garments and payments, and forms to add to either.",
  "laundrySales.sum.balance": "What is still owed. Settled: nothing owed.",
  "laundrySales.sum.total": "Everything on the bill.",
  "laundrySales.sum.paid": "Everything paid towards it.",
  "laundrySales.charges": "Every garment on the bill, with whether each is paid. Add more below.",
  "laundrySales.customer": "The customer's name and phone, if the bill needs tracing later. Can be added any time.",
  "laundrySales.customer.name": "The customer's name.",
  "laundrySales.customer.phone": "The customer's phone number.",
  "laundrySales.creditOnFile": "Money this customer overpaid on an earlier bill. Apply Credit puts it towards this one.",
  "laundrySales.recordPayment": "Record money paid towards the bill. Anything paid over the balance is kept on file as credit.",
  "laundrySales.receipt": "The number on the paper receipt. Leave it blank and the system makes one.",
  "laundrySales.notes": "Anything worth noting about this payment.",
  // ---- Reports
  "reports.shift": "Who was on duty. It is written on the Excel export; the Manifest, Food Sales, Drink Sales and Bar Stock need it before they export.",
  "reports.from": "The first business day to include. A business day runs 6am to 6am.",
  "reports.to": "The last business day to include.",
  "reports.date": "The business day to report on: 6am that day to 6am the next.",
  "reports.col.action": "View log: opens the Audit Trail at who did this, over the report's dates.",
  "reports.dash.totalBilled": "Everything charged in these dates, to guests and non-guests.",
  "reports.dash.paymentsReceived": "Money taken in these dates, less refunds. The same as the Analysis report's Net Total.",
  "reports.dash.outstanding": "What stays that began in these dates still owe.",
  "reports.dash.completedStays": "Stays that began in these dates and have checked out, out of all that began.",
  "reports.dash.revenueByType": "Room and breakfast charged for the nights in these dates, by room type.",
  "reports.dash.col.roomType": "The room type.",
  "reports.dash.col.stays": "Stays billed nights of this type in these dates. A stay that changed type counts under both.",
  "reports.dash.col.revenue": "Room and breakfast charged for those nights.",
  "reports.dash.col.avgStay": "Revenue divided by stays.",
  "reports.dash.paymentsByMethod": "Payments and non-guest sales, less refunds, by how they were paid.",
  "reports.dash.col.method": "How it was paid.",
  "reports.dash.col.count": "How many payments.",
  "reports.dash.col.total": "Their total, less refunds.",
  "reports.dash.col.share": "This method's part of all money taken.",
  "reports.dash.occupancy": "Room-nights booked against room-nights there were, by room type. No-shows are left out.",
  "reports.dash.col.capacity": "How many rooms of this type the hotel has.",
  "reports.dash.col.availNights": "Rooms of this type times the nights in these dates.",
  "reports.dash.col.occupied": "Room-nights booked.",
  "reports.dash.col.occPct": "Occupied divided by available nights. Green: 80% or more. Yellow: 50% or more.",
  "reports.manifest.checkIns": "Everyone due to arrive this business day.",
  "reports.manifest.checkOuts": "Everyone due to leave this business day.",
  "reports.manifest.col.guest": "The guest, with any VIP or Blacklisted tag.",
  "reports.manifest.col.room": "The room numbers, or Unassigned.",
  "reports.manifest.col.roomPrice": "The room's price for the stay.",
  "reports.manifest.col.breakfast": "The breakfast price for the stay.",
  "reports.manifest.col.receipt": "The receipt numbers of the guest's payments.",
  "reports.manifest.col.resCredit": "Money paid ahead for this booking.",
  "reports.manifest.col.arrival": "When the guest arrived, or is due to.",
  "reports.manifest.col.checkOut": "When the guest left, or is due to.",
  "reports.manifest.col.source": "How the booking came in: walk-in, website or OTA.",
  "reports.roomRevenueTotal": "The room money for these stays. Breakfast and complementary rooms are left out.",
  "reports.analysis.collected": "Guest payments and non-guest sales taken in these dates.",
  "reports.analysis.refunded": "Payments and credit paid back in these dates.",
  "reports.analysis.net": "Collected minus refunded: the money the hotel kept. The same as the Overview's Collected for these dates.",
  "reports.analysis.all": "Every payment, non-guest sale, refund and credit refund in these dates.",
  "reports.analysis.col.room": "The guest's room numbers.",
  "reports.analysis.col.receipt": "The number on the paper receipt.",
  "reports.analysis.col.reference": "The payment's own reference. Search it on Folios.",
  "reports.analysis.col.guest": "Who paid. Tagged when it is a non-guest sale, a refund or a credit refund.",
  "reports.analysis.col.method": "How it was paid.",
  "reports.analysis.col.date": "When it was paid.",
  "reports.analysis.col.amount": "How much. Red with a minus: money paid back.",
  "reports.netTotal": "Collected minus refunded.",
  "reports.pms.variant": "Evening (about 7pm) for the end of the day. Morning (about 7am) to see last night's audit.",
  "reports.pms.stayOvers": "Guests in-house who are neither arriving nor leaving today.",
  "reports.pms.col.guest": "The guest, with any VIP or Blacklisted tag.",
  "reports.pms.col.checkIn": "When the guest checked in.",
  "reports.pms.col.checkOut": "The day the guest is booked to leave.",
  "reports.pms.arrivals": "Guests due to arrive on this day.",
  "reports.pms.arrivals.status": "Arrived, or Still Expected.",
  "reports.pms.departures": "Guests due to leave on this day.",
  "reports.pms.departures.status": "Departed, or Still In-House.",
  "reports.pms.roomStatus": "Every room by its status, with the room numbers.",
  "reports.pms.vacant": "Rooms free to sell.",
  "reports.pms.occupied": "Rooms with a guest in them.",
  "reports.pms.ooo": "Rooms needing repair, not sold.",
  "reports.pms.reserved": "Rooms set aside, e.g. for a manager.",
  "reports.pms.complementary": "Rooms given free to their guest.",
  "reports.acc.rooms": "One row per room in use this night: who is in it, its tariff, and what was paid for it today.",
  "reports.acc.col.guest": "The guest, with any VIP or Blacklisted tag.",
  "reports.acc.col.roomType": "The room's type.",
  "reports.acc.col.roomNo": "The room number.",
  "reports.acc.col.arrivalDate": "The day the guest arrived.",
  "reports.acc.col.arrivalTime": "The time the guest arrived.",
  "reports.acc.col.checkoutDate": "The day the guest leaves, or left.",
  "reports.acc.col.checkoutTime": "The time the guest left. Blank until they have.",
  "reports.acc.col.tariff": "The room's price for the night.",
  "reports.acc.col.paymentMode": "How the night was paid.",
  "reports.acc.col.paymentStatus": "Paid, Owing, or PB: paid before, from credit taken on an earlier day.",
  "reports.acc.col.receipt": "The receipt of the payment that settled this night. NIL while it is owing.",
  "reports.acc.col.paidToday": "Money the guest paid today.",
  "reports.acc.col.counted": "What this room adds to the Manifest Total: room money paid fresh today. A PB room adds nothing.",
  "reports.acc.col.refund": "Money handed back to the guest today. NIL when none.",
  "reports.acc.col.guestStatus": "Checked In (arrived today), Stay Over (here from before), or Checked In & Out (arrived and left the same day).",
  "reports.acc.col.remarks": "How the booking came in: walk-in, website or OTA.",
  "reports.acc.manifestTotal": "The sum of Counted in Total: room money guests paid today. Breakfast is left out.",
  "reports.acc.nonRevenue": "Rooms in use that bring in no money: complementary stays and managers' rooms.",
  "reports.acc.nonRevenue.col.room": "The room number.",
  "reports.acc.nonRevenue.col.name": "Who is in it. Manager for a manager's room.",
  "reports.acc.nonRevenue.col.status": "Complementary or Manager.",
  "reports.acc.byMethod": "The day's money, one list per payment method, for checking each drawer or account. Refunds are taken off their method.",
  "reports.acc.byMethod.col.guest": "Who paid. Tagged when it is a non-guest sale, a refund or a credit refund.",
  "reports.acc.byMethod.col.room": "The guest's room numbers.",
  "reports.acc.byMethod.col.amount": "How much. A minus: money paid back.",
  "reports.acc.byMethod.col.receipt": "The receipt number, or the payment's reference.",
  "reports.acc.byMethod.col.time": "When it was paid.",
  "reports.acc.reservation": "Money paid ahead today for stays to come.",
  "reports.acc.reservation.col.guest": "The guest the booking is for.",
  "reports.acc.reservation.col.room": "The booking's room numbers.",
  "reports.acc.reservation.col.amount": "How much was paid ahead.",
  "reports.acc.reservation.col.method": "How it was paid.",
  "reports.acc.reservation.col.status": "Pending: not yet used. Applied: put towards the stay. Refunded: paid back.",
  "reports.acc.reservation.col.receipt": "The number on the paper receipt.",
  "reports.acc.reservationTotal": "Money paid ahead today.",
  "reports.acc.manifestPlusReservation": "The Manifest Total and the Reservation Total added together.",
  "reports.acc.debt": "Old debt that a payment today cleared.",
  "reports.acc.debt.col.guest": "The guest who owed.",
  "reports.acc.debt.col.room": "Their room numbers.",
  "reports.acc.debt.col.dateOwed": "The business day the debt was run up.",
  "reports.acc.debt.col.owed": "What was owed.",
  "reports.acc.debt.col.paid": "What was paid today towards it.",
  "reports.acc.debt.col.method": "How it was paid.",
  "reports.acc.debt.col.reference": "The payment's own reference.",
  "reports.acc.debtTotal": "Old debt paid today.",
  "reports.acc.grand": "The Manifest Total, the Reservation Total and the Debt Recovery Total added together.",
  "reports.acc.grandLine": "Everything counted on this Manifest for the day.",
  "reports.acc.notes": "Today's charges that are neither room nor food and drink, e.g. laundry, penalties and corrections, then the guests' own notes.",
  "reports.acc.notes.col.guest": "Whose bill it went on.",
  "reports.acc.notes.col.room": "Their room numbers.",
  "reports.acc.notes.col.type": "What kind of charge.",
  "reports.acc.notes.col.description": "What the charge was for.",
  "reports.acc.notes.col.remarks": "Anything noted with it.",
  "reports.acc.notes.col.amount": "How much. A minus: money taken off the bill.",
  "reports.sales.total": "Everything sold today, service charge included.",
  "reports.sales.method": "What was sold paid this way. Charged to Room: put on a guest's folio, not yet paid.",
  "reports.sales.food": "Every food order today, on a guest's folio or a non-guest bill.",
  "reports.sales.drink": "Every drink order today, on a guest's folio or a non-guest bill.",
  "reports.sales.col.customer": "The guest or customer.",
  "reports.sales.col.qty": "How many.",
  "reports.sales.col.billNo": "The number on the paper bill.",
  "reports.sales.col.description": "What was ordered.",
  "reports.sales.col.amount": "The price, before service charge.",
  "reports.sales.col.serviceCharge": "The service charge added.",
  "reports.sales.col.status": "Paid, Owing, PB (paid from earlier credit), Complementary or Manager.",
  "reports.sales.col.method": "How it was paid.",
  "reports.sales.col.remarks": "Anything noted with the order.",
  "reports.sales.notes": "The day's figures in a line each: methods, paid before, debt, total sold, service charge, and credit taken for later.",
  "reports.sales.byStaff": "Who rang up the orders, and their total.",
  "reports.sales.byStaff.col.staff": "The staff member.",
  "reports.sales.byStaff.col.total": "What they rang up.",
  "reports.bar.totalSold": "How many drinks sold today.",
  "reports.bar.totalAmount": "What the drinks sold for, service charge included.",
  "reports.bar.stock": "Each drink's movements today.",
  "reports.bar.col.stock": "The drink.",
  "reports.bar.col.opening": "In stock at the start of the day.",
  "reports.bar.col.added": "Added today.",
  "reports.bar.col.totalBefore": "Opening plus added.",
  "reports.bar.col.damaged": "Written off as damaged today.",
  "reports.bar.col.sold": "Sold today.",
  "reports.bar.col.unitPrice": "The drink's menu price.",
  "reports.bar.col.totalAmount": "What it sold for today, service charge included.",
  "reports.bar.col.closing": "Left at the end of the day. Red: below zero, so a count or a sale needs checking.",
  "reports.bar.col.serviceCharge": "The service charge part of Total Amount.",
  "reports.bar.col.remark": "Notes recorded with today's stock movements.",
  "reports.bar.daily": "Food and drink together for the business day.",
  "reports.bar.food": "Food sold today.",
  "reports.bar.drink": "Drinks sold today.",
  "reports.bar.serviceCharge": "Service charge on today's food and drink.",
  "reports.bar.debtRecovered": "Old food and drink debt paid today.",
  "reports.bar.cash": "Food and drink paid in cash.",
  "reports.bar.pos": "Food and drink paid by card or POS.",
  "reports.bar.transfer": "Food and drink paid by transfer or online.",
  "reports.bar.chargedToRoom": "Food and drink put on guests' folios, not yet paid.",
  "reports.bar.reservationCredit": "Credit taken today for later use. Not counted in the total.",
  "reports.bar.debt": "Food and drink sold today still owing.",
  "reports.bar.paidBefore": "Food and drink paid from credit taken on an earlier day.",
  "reports.bar.total": "Money actually taken against food and drink today, including old debt paid.",
  "reports.byStaff": "Who checked guests in and out and took payments, each counted on its own.",
  "reports.byStaff.checkIns": "Guests each staff member checked in.",
  "reports.byStaff.checkOuts": "Guests each staff member checked out.",
  "reports.byStaff.payments": "Payments each staff member took, and their total.",
  "reports.byStaff.col.date": "The business day.",
  "reports.byStaff.col.staff": "The staff member.",
  "reports.byStaff.col.guests": "How many guests.",
  "reports.byStaff.col.count": "How many payments.",
  "reports.byStaff.col.amount": "Their total.",
  // ---- Night Audit
  "nightAudit.run": "Close a business day by hand if the 6am run hasn't: it posts that night's room charges.",
  "nightAudit.date": "The business day to close. Yesterday at the latest.",
  "nightAudit.dateAudited": "The business day that was closed.",
  "nightAudit.guestsCharged": "Stays charged for the night.",
  "nightAudit.totalPosted": "The room charges posted, in total.",
  "nightAudit.skipped": "Stays not charged, each with its reason below, e.g. already charged or a complementary room.",
  "nightAudit.col.guest": "The guest, with their booking reference.",
  "nightAudit.col.roomType": "The room type charged, and how many rooms.",
  "nightAudit.col.folio": "The folio the charge went on.",
  "nightAudit.col.charge": "The night's charge.",
  "nightAudit.col.status": "Posted, or Skipped with the reason.",
  "nightAudit.history": "Every business day closed so far, newest first.",
  "nightAudit.col.businessDate": "The business day closed.",
  "nightAudit.col.guestsCharged": "Stays charged.",
  "nightAudit.col.skipped": "Stays not charged.",
  "nightAudit.col.totalPosted": "The room charges posted.",
  "nightAudit.col.runAt": "When the audit ran.",
  "nightAudit.col.source": "Auto: the 6am run. Manual: run from this page.",
  // ---- Alerts
  "alerts.col.guest": "The guest, with their booking reference.",
  "alerts.col.roomType": "The room type booked.",
  "alerts.missed.checkInWas": "The arrival day, and how long ago it was.",
  "alerts.col.status": "Where the booking stands.",
  "alerts.missed.actions": "View: opens the booking. No-Show: marks the guest as not coming and frees the room.",
  "alerts.unconfirmed.booked": "How long ago the booking was made.",
  "alerts.unconfirmed.expires": "Time left before the room is released. Expired - reclaimable: released, but Reclaim Hold on the booking can take it back.",
  "alerts.unconfirmed.actions": "View: opens the booking, to confirm it once paid.",
  "alerts.overdue.wasDueOut": "The booked check-out day, and how long ago it was.",
  "alerts.overdue.actions": "Go to In-House: check the guest out, or extend the stay.",
  "alerts.balances.folio": "The guest's folio number.",
  "alerts.balances.checkedOut": "The day the guest left.",
  "alerts.balances.due": "What the guest still owes.",
  "alerts.balances.actions": "Go to Folio: record the payment.",
  "alerts.credits.credit": "The money still on the folio.",
  "alerts.credits.taken": "When the money was paid.",
  "alerts.credits.checkedOut": "When the guest left.",
  "alerts.credits.actions": "View: opens the folio, to refund the credit or move it to a booking the guest has now.",
  "alerts.flagged.when": "The business day it belongs to (6am to 6am): a refund at 1am is the night before.",
  "alerts.flagged.what": "What the accountant flagged, and its details.",
  "alerts.flagged.amount": "Money paid back, taken off a bill (negative), given as a discount, or free food and drink at menu price.",
  "alerts.flagged.by": "Who did it.",
  "alerts.flagged.note": "What the accountant wants you to look at, and when they flagged it.",
  // ---- OTA Payments
  "otaPayments.awaiting": "Everything the OTAs still owe across these bookings.",
  "otaPayments.col.guest": "The guest, with any VIP or Blacklisted tag.",
  "otaPayments.col.bookingRef": "The booking's reference.",
  "otaPayments.col.nights": "The nights the OTA pays for: from the first night to the morning they end.",
  "otaPayments.col.covers": "Room only, or room and breakfast.",
  "otaPayments.col.amount": "What the OTA will send.",
  "otaPayments.col.status": "Owing: not yet received. Paid: received.",
  "otaPayments.col.action": "Mark Paid: once the OTA's money has arrived. Paid ones show the OTA's reference.",
  "otaPayments.reference": "The OTA's own reference for the transfer, if it gave one.",
  // ---- Account
  "account.changePassword": "Change the password you sign in with.",
  "account.current": "The password you sign in with now.",
  "account.new": "At least 8 characters, different from the current one.",
  "account.confirm": "The new password again, to catch a typo.",
  // ---- Sign-in and shell
  "signIn.form": "One sign-in for every branch and Head Office. Your account opens the right place.",
  "signIn.username": "Your PMS username.",
  "signIn.password": "Your PMS password. The eye shows or hides it.",
  "branchPicker.place": "The branch, or Head Office, to open.",
  "topBar.shift": "Who is on duty this business day: what is done today is put under their name. Change corrects a wrong pick, and the change is logged.",
  "topBar.user": "Who is signed in, and their role.",
  "topBar.viewAs": "See the PMS as another role sees it, to check what they can open.",
  "shiftGate.person": "Who is on duty today: yourself, or the colleague whose shift it is.",
  "help.jump": "Press a page's name to scroll to its guide.",
  // ---- Audit Trail
  "auditTrail.branch": "Which branch's record to read, or Head Office's own.",
  "auditTrail.search": "Find entries by a guest's name, a staff member or the action.",
  "auditTrail.staff": "Only what one staff member did.",
  "auditTrail.role": "Only what one role did. Auto (PMS): what the system did by itself, e.g. the night audit.",
  "auditTrail.action": "Only one kind of action, e.g. check-ins or payments.",
  "auditTrail.from": "The first day to show.",
  "auditTrail.to": "The last day to show.",
  "auditTrail.col.staff": "Who did it.",
  "auditTrail.col.when": "When they did it.",
  "auditTrail.col.role": "Their role.",
  "auditTrail.col.action": "What was done, in plain words. A link opens what it was done to.",
  // ---- Menu
  "menu.showInactive": "Also lists items set out of stock.",
  "menu.col.name": "The item.",
  "menu.col.price": "What one costs. Orders charge this price.",
  "menu.col.serviceCharge": "Added on top of the price for each one sold.",
  "menu.col.stock": "How many are in stock, from restocks, breakages, sales and counts.",
  "menu.col.status": "In Stock or Out of Stock. Drinks follow their stock; Not Tracked: no stock recorded yet.",
  "menu.col.actions": "Edit: name and prices. Set Out of Stock / Mark In Stock. Adjust Stock (drinks): a restock, a breakage or a count. Delete: after you confirm.",
  "menu.stock.type": "Added: a restock. Damaged: breakage, spillage or expiry. Correction: the real count on the shelf.",
  "menu.stock.quantity": "How many. For a correction, the total counted, not a plus or minus.",
  "menu.stock.notes": "Anything worth noting. It shows on the Bar Stock report.",
  "menu.add": "Add an item to the menu. Managers, accountants and store keepers.",
  "menu.add.name": "What the item is called on order forms and receipts.",
  "menu.add.price": "What one costs.",
  "menu.add.serviceCharge": "Added on top of the price for each one sold. 0 for none.",
  "menu.laundry.showInactive": "Also lists deactivated garments.",
  "menu.laundry.col.clothes": "The garment.",
  "menu.laundry.col.washIron": "The price to wash and iron one.",
  "menu.laundry.col.ironOnly": "The price to iron one.",
  "menu.laundry.col.status": "Active: offered. Inactive: not offered.",
  "menu.laundry.col.actions": "Edit: name and prices. Deactivate / Reactivate. Delete: refused once a garment has been sold.",
  "menu.laundry.add": "Add a garment. At least one price is needed.",
  "menu.laundry.add.clothes": "The garment, e.g. Shirt.",
  "menu.laundry.add.washIron": "The price to wash and iron one.",
  "menu.laundry.add.ironOnly": "The price to iron one.",
  // ---- Metrics
  "metrics.col.branch": "The branch. Press a column's title to sort by it.",
  "metrics.select": "Which metric to show.",
  "metrics.presets": "Quick date ranges.",
  "metrics.from": "The first day to include.",
  "metrics.to": "The last day to include.",
  "metrics.branchChoice": "Show one branch, or all of them.",
  "metrics.showKind": "Food, drinks, or both.",
  "metrics.collections.method": "Money taken this way, less refunds paid back this way.",
  "metrics.channels.tile.walk_in": "Walk-ins' share of room revenue.",
  "metrics.channels.tile.website": "The website's share of room revenue.",
  "metrics.occupancy.tile.group-occupancy": "Room-nights sold across every branch, against the rooms they had.",
  "metrics.occupancy.tile.room-nights-sold": "Nights of rooms sold in these dates, all branches together.",
  "metrics.occupancy.tile.fullest-branch": "The branch with the highest occupancy.",
  "metrics.occupancy.rooms": "Rooms the branch has.",
  "metrics.occupancy.sold": "Nights of rooms sold.",
  "metrics.occupancy.available": "Rooms times days in these dates.",
  "metrics.occupancy.occupancy": "Sold against available.",
  "metrics.occupancy.prev": "Occupancy over the same length of time just before.",
  "metrics.occupancy.change": "The difference from the previous period, in percentage points.",
  "metrics.occupancy.section1": "Each branch's occupancy day by day (or month by month); darker is fuller. Point at a square for its figures.",
  "metrics.adr-revpar.tile.room-revenue": "Room charges posted in these dates, breakfast apart.",
  "metrics.adr-revpar.room_revenue": "Room charges posted, breakfast apart.",
  "metrics.adr-revpar.sold": "Nights of rooms sold.",
  "metrics.adr-revpar.occupancy": "Sold against available.",
  "metrics.trevpar.tile.total-revenue": "Everything charged in these dates, to guests and non-guests.",
  "metrics.trevpar.tile.beyond-rooms": "The part of revenue that isn't room charges.",
  "metrics.trevpar.total_revenue": "Everything charged.",
  "metrics.trevpar.room_revenue": "Room charges, breakfast apart.",
  "metrics.trevpar.beyond": "The share of revenue from beyond rooms.",
  "metrics.revenue-mix.tile.total-revenue": "Everything charged in these dates.",
  "metrics.revenue-mix.tile.rooms": "Room charges' share of revenue.",
  "metrics.revenue-mix.tile.food-and-drink": "Food and drink's share of revenue.",
  "metrics.revenue-mix.rooms": "Room charges, and their share of the total.",
  "metrics.revenue-mix.breakfast": "Breakfast charges.",
  "metrics.revenue-mix.food": "Food.",
  "metrics.revenue-mix.drinks": "Drinks.",
  "metrics.revenue-mix.laundry": "Laundry.",
  "metrics.revenue-mix.other": "Other charges, e.g. penalties.",
  "metrics.revenue-mix.adjustments": "Amounts taken off bills, or put back.",
  "metrics.revenue-mix.total": "Everything charged: the Dashboard's Total Billed.",
  "metrics.stay-length.tile.average-stay": "Nights per stay, on average.",
  "metrics.stay-length.tile.one-night-stays": "The share of stays that were one night.",
  "metrics.stay-length.tile.website-lead-time": "Days from booking to arrival for website bookings, on average.",
  "metrics.stay-length.stays": "Stays that began in these dates.",
  "metrics.stay-length.avg": "Nights per stay, on average.",
  "metrics.stay-length.one": "One-night stays.",
  "metrics.stay-length.two": "Stays of two or three nights.",
  "metrics.stay-length.four": "Stays of four to seven nights.",
  "metrics.stay-length.week": "Stays of more than seven nights.",
  "metrics.stay-length.walk_in": "Walk-in stays' average length.",
  "metrics.stay-length.website": "Website stays' average length, and how far ahead they booked.",
  "metrics.channels.walk_in": "Room and breakfast from walk-ins, and their share.",
  "metrics.channels.website": "Room and breakfast from website bookings, and their share.",
  "metrics.channels.revenue": "Room and breakfast charged in these dates.",
  "metrics.channels.stays": "Stays charged in these dates.",
  "metrics.cancellations.tile.cancelled-after-booking": "Bookings due in these dates that were cancelled.",
  "metrics.cancellations.tile.website-bookings-never-paid": "Website bookings released because payment never came.",
  "metrics.cancellations.tile.no-shows-marked": "Guests marked as never arriving.",
  "metrics.cancellations.bookings": "Bookings due to arrive in these dates.",
  "metrics.cancellations.stayed": "Bookings that arrived.",
  "metrics.cancellations.cancelled": "Bookings cancelled.",
  "metrics.cancellations.cancel_pct": "Cancelled against bookings.",
  "metrics.cancellations.no_shows": "Bookings marked no-show.",
  "metrics.cancellations.website": "Website bookings due.",
  "metrics.cancellations.lapsed": "Website bookings never paid for.",
  "metrics.cancellations.lapse_pct": "Never paid against website bookings.",
  "metrics.discounts.tile.discounts-given": "Money below the standard price, all stays together.",
  "metrics.discounts.tile.average-discount": "How far below standard, on average, where a discount was given.",
  "metrics.discounts.tile.largest-single-discount": "The biggest single discount, and who set it.",
  "metrics.discounts.stays": "Stays that began in these dates.",
  "metrics.discounts.discounted": "Stays charged below standard.",
  "metrics.discounts.discounted_pct": "Discounted stays' share.",
  "metrics.discounts.discount": "Everything below standard.",
  "metrics.discounts.avg": "The average discount, where one was given.",
  "metrics.discounts.staff.branch": "Their branch.",
  "metrics.discounts.staff.discounted": "Stays they discounted.",
  "metrics.discounts.staff.discount": "Everything they gave off.",
  "metrics.discounts.staff.largest": "Their biggest single discount.",
  "metrics.discounts.staff.__first": "Who set the rate: whoever checked the guest in.",
  "metrics.discounts.largest.branch": "The branch.",
  "metrics.discounts.largest.type": "The room type.",
  "metrics.discounts.largest.check_in": "The arrival day.",
  "metrics.discounts.largest.nights": "Nights stayed.",
  "metrics.discounts.largest.standard": "The standard price for those nights.",
  "metrics.discounts.largest.charged": "What was charged.",
  "metrics.discounts.largest.discount": "Standard minus charged.",
  "metrics.discounts.largest.set_by": "Who set the rate.",
  "metrics.discounts.largest.__first": "The guest.",
  "metrics.discounts.section1": "Discounts by who set the rate.",
  "metrics.discounts.section2": "The biggest discounts in these dates.",
  "metrics.complimentary.tile.nights-with-no-room-charge": "Nights a guest slept with no room charge.",
  "metrics.complimentary.tile.worth-at-standard-prices": "Those nights at standard prices.",
  "metrics.complimentary.tile.complimentary-rooms-now": "Rooms marked complimentary right now.",
  "metrics.complimentary.stays": "Stays with such a night.",
  "metrics.complimentary.nights": "Nights with no room charge.",
  "metrics.complimentary.worth": "Those nights at standard prices.",
  "metrics.complimentary.now": "Rooms complimentary now.",
  "metrics.complimentary.stays.branch": "The branch.",
  "metrics.complimentary.stays.rooms": "The room numbers.",
  "metrics.complimentary.stays.type": "The room type.",
  "metrics.complimentary.stays.nights": "Nights with no room charge.",
  "metrics.complimentary.stays.when": "The first and last of those nights.",
  "metrics.complimentary.stays.worth": "Those nights at standard prices.",
  "metrics.complimentary.stays.__first": "The guest.",
  "metrics.complimentary.section1": "Each stay with a night that had no room charge.",
  "metrics.out-of-order.tile.rooms-out-of-order": "Rooms out of order now.",
  "metrics.out-of-order.tile.potential-loss": "Bookings they may have cost: the low end one room per sold-out night, the high end every room out.",
  "metrics.out-of-order.tile.counted-to": "The last night counted.",
  "metrics.out-of-order.sold_out": "Nights the room type sold every room it had for sale.",
  "metrics.out-of-order.lost": "The potential loss, low to high.",
  "metrics.collections.tile.collected": "Money taken, less money paid back.",
  "metrics.collections.tile.paid-back-out": "Refunds and credit refunds.",
  "metrics.collections.tile.cash-share": "Cash's part of the money collected.",
  "metrics.collections.in": "Payments and non-guest sales.",
  "metrics.collections.out": "Refunds and credit refunds.",
  "metrics.collections.net": "Money in less money paid back: the Overview's Collected.",
  "metrics.collections.cash": "Cash's share of collected.",
  "metrics.collections.section1": "Money collected each business day; darker is more. Point at a square for its figure.",
  "metrics.outstanding.tile.owed-by-guests": "Open guest bills with a balance.",
  "metrics.outstanding.tile.owed-by-non-guests": "Open non-guest bills with a balance.",
  "metrics.outstanding.tile.owed-over-30-days": "Owed by guests who left more than a month ago.",
  "metrics.outstanding.in_house": "Owed by guests staying now.",
  "metrics.outstanding.d0_7": "Owed by guests who left in the last week.",
  "metrics.outstanding.d8_30": "Owed by guests who left 8 to 30 days ago.",
  "metrics.outstanding.d31_plus": "Owed by guests who left over 30 days ago.",
  "metrics.outstanding.other": "Other guest bills with a balance.",
  "metrics.outstanding.non_guests": "Open non-guest bills.",
  "metrics.outstanding.total": "Everything owed.",
  "metrics.outstanding.chase.branch": "The branch.",
  "metrics.outstanding.chase.kind": "A guest who has left, or a non-guest.",
  "metrics.outstanding.chase.amount": "What they owe.",
  "metrics.outstanding.chase.days": "How long it has been owed.",
  "metrics.outstanding.chase.__first": "Who owes.",
  "metrics.outstanding.section1": "The longest-standing debts.",
  "metrics.ota.tile.longest-wait": "Days since the nights of the oldest unpaid OTA payment ended.",
  "metrics.ota.tile.received-in-these-dates": "OTA money received in these dates.",
  "metrics.ota.waiting": "What OTAs owe now.",
  "metrics.ota.oldest": "The oldest unpaid payment's wait.",
  "metrics.ota.received": "Received in these dates.",
  "metrics.ota.avg_days": "Days from the end of the nights to payment, on average.",
  "metrics.ota.waiting.branch": "The branch.",
  "metrics.ota.waiting.nights": "The nights the OTA pays for.",
  "metrics.ota.waiting.amount": "What the OTA will send.",
  "metrics.ota.waiting.waiting": "Days since those nights ended.",
  "metrics.ota.waiting.__first": "The guest.",
  "metrics.ota.section1": "OTA payments not yet received.",
  "metrics.credit-held.tile.credit-held": "Money paid in, not yet spent or given back.",
  "metrics.credit-held.tile.to-chase": "Credit for guests who left, or on cancelled bookings.",
  "metrics.credit-held.tile.non-guest-credit": "Overpayments by non-guests.",
  "metrics.credit-held.in_house": "Credit of guests staying now.",
  "metrics.credit-held.upcoming": "Credit on bookings still to arrive.",
  "metrics.credit-held.departed": "Credit of guests who left.",
  "metrics.credit-held.cancelled": "Credit on cancelled bookings.",
  "metrics.credit-held.other": "Other guest credit.",
  "metrics.credit-held.non_guests": "Non-guest overpayments.",
  "metrics.credit-held.total": "All credit held.",
  "metrics.credit-held.chase.branch": "The branch.",
  "metrics.credit-held.chase.stay": "Left, or Cancelled.",
  "metrics.credit-held.chase.amount": "The credit.",
  "metrics.credit-held.chase.since": "When it was paid.",
  "metrics.credit-held.chase.__first": "The guest.",
  "metrics.credit-held.section1": "Credit to refund, or move to a booking the guest has.",
  "metrics.exceptions.tile.given-back-or-taken-off": "Refunds, credit refunds, adjustments, corrections, rate discounts and free F&B together.",
  "metrics.exceptions.tile.refunds-and-credit-refunds": "Money paid back out.",
  "metrics.exceptions.refunds": "Payments refunded.",
  "metrics.exceptions.credit_refunds": "Credit paid back out.",
  "metrics.exceptions.adjustments": "Taken off bills by adjustments.",
  "metrics.exceptions.corrections": "Taken off bills by corrections.",
  "metrics.exceptions.discounts": "Rates below standard.",
  "metrics.exceptions.total": "All of these together.",
  "metrics.exceptions.staff.branch": "Their branch.",
  "metrics.exceptions.staff.role": "Their role.",
  "metrics.exceptions.staff.refunds": "Refunds they made, and how many.",
  "metrics.exceptions.staff.credit_refunds": "Credit they paid back, and how many.",
  "metrics.exceptions.staff.adjustments": "What their adjustments took off.",
  "metrics.exceptions.staff.corrections": "What their corrections took off.",
  "metrics.exceptions.staff.discounts": "Rates they set below standard.",
  "metrics.exceptions.staff.total": "All of these together.",
  "metrics.exceptions.staff.__first": "Who did it.",
  "metrics.exceptions.section1": "Each kind, under whoever did it.",
  "metrics.repeat-guests.tile.returning-guests": "The share who had stayed with the group before.",
  "metrics.repeat-guests.tile.guests-who-checked-in": "People who checked in, each counted once.",
  "metrics.repeat-guests.tile.first-stayed-at-another-branch": "Returning guests whose first stay was at another branch.",
  "metrics.repeat-guests.guests": "Guests who checked in.",
  "metrics.repeat-guests.returning": "Of them, those who had stayed before.",
  "metrics.repeat-guests.share": "Returning against all.",
  "metrics.repeat-guests.elsewhere": "Returning guests whose first stay was elsewhere.",
  "metrics.top-guests.stays": "Stays, all time.",
  "metrics.top-guests.nights": "Nights, all time.",
  "metrics.top-guests.billed": "What their stays were billed.",
  "metrics.top-guests.last": "Their latest stay.",
  "metrics.top-guests.branches": "Where they have stayed.",
  "metrics.top-guests.__first": "The guest, ranked by stays.",
  "metrics.top-guests.first": "Their first stay.",
  "metrics.contactability.tile.bookings-with-an-email": "Bookings with an email address.",
  "metrics.contactability.tile.bookings-with-a-phone-number": "Bookings with a phone number.",
  "metrics.contactability.tile.emails-bounced": "Emails that couldn't be delivered.",
  "metrics.contactability.bookings": "Bookings due in these dates.",
  "metrics.contactability.phone": "With a phone number.",
  "metrics.contactability.phone_pct": "Their share.",
  "metrics.contactability.email": "With an email address.",
  "metrics.contactability.email_pct": "Their share.",
  "metrics.contactability.bounced": "Emails that bounced.",
  "metrics.fnb-sales.tile.per-room-night-sold": "F&B sales per room-night sold.",
  "metrics.fnb-sales.tile.from-non-guests": "Sales to non-guests.",
  "metrics.fnb-sales.food": "Food sold.",
  "metrics.fnb-sales.drinks": "Drinks sold.",
  "metrics.fnb-sales.guests": "Sold to guests.",
  "metrics.fnb-sales.non_guests": "Sold to non-guests.",
  "metrics.fnb-sales.per": "Per room-night sold.",
  "metrics.top-items.kind": "Food or drink.",
  "metrics.top-items.quantity": "Units sold.",
  "metrics.top-items.orders": "Orders it was on.",
  "metrics.top-items.sales": "What it sold for.",
  "metrics.top-items.free": "Units given free.",
  "metrics.top-items.branches": "Where it sold.",
  "metrics.top-items.__first": "The menu item.",
  "metrics.fnb-comp.tile.given-away": "Free food and drink, at menu price.",
  "metrics.fnb-comp.tile.complimentary": "Given free to guests.",
  "metrics.fnb-comp.tile.manager-s": "The manager's own consumption.",
  "metrics.fnb-comp.complimentary": "Complimentary, at menu price.",
  "metrics.fnb-comp.manager": "The manager's, at menu price.",
  "metrics.fnb-comp.worth": "Both together.",
  "metrics.bar-stock.tile.out-of-stock": "Drinks with none on the shelf.",
  "metrics.bar-stock.tile.running-low": "Drinks with under a week's sales left.",
  "metrics.bar-stock.tile.written-off": "Units damaged or found missing.",
  "metrics.bar-stock.items": "Drinks tracked.",
  "metrics.bar-stock.units": "Units on the shelf now.",
  "metrics.bar-stock.out": "Drinks out of stock.",
  "metrics.bar-stock.below": "Drinks below zero: more sold than came in.",
  "metrics.bar-stock.low": "Drinks running low.",
  "metrics.bar-stock.sold": "Units sold.",
  "metrics.bar-stock.added": "Units added.",
  "metrics.bar-stock.written_off": "Units written off.",
  "metrics.bar-stock.loss": "Written off against what left the shelf.",
  "metrics.bar-stock.attention.branch": "The branch.",
  "metrics.bar-stock.attention.state": "Below zero, out of stock, or running low.",
  "metrics.bar-stock.attention.now": "Units on the shelf now.",
  "metrics.bar-stock.attention.sold": "Units sold in these dates.",
  "metrics.bar-stock.attention.days": "Days left at this pace.",
  "metrics.bar-stock.attention.__first": "The drink.",
  "metrics.bar-stock.section1": "Drinks out, below zero or running low.",
  "metrics.night-audits.tile.nights-audited": "Nights audited, of all nights at all branches.",
  "metrics.night-audits.tile.missed": "Nights with no audit.",
  "metrics.night-audits.tile.run-by-hand": "Audits run from the PMS instead of at 6am.",
  "metrics.night-audits.nights": "Nights that ended in these dates.",
  "metrics.night-audits.ran": "Audits that ran.",
  "metrics.night-audits.missed": "Nights with no audit, and which.",
  "metrics.night-audits.automatic": "Ran by themselves at 6am.",
  "metrics.night-audits.by_hand": "Run from the PMS.",
  "metrics.night-audits.rooms": "Rooms the audits charged.",
  "metrics.night-audits.posted": "Room charges posted.",
  "metrics.night-audits.last": "The latest audit.",
  "metrics.staff-activity.tile.people-who-did-anything": "Staff with at least one check-in, payment, order or shift.",
  "metrics.staff-activity.tile.check-ins": "Guests checked in.",
  "metrics.staff-activity.tile.money-taken": "Payments taken, less refunds.",
  "metrics.staff-activity.branch": "Their branch.",
  "metrics.staff-activity.check_ins": "Guests they checked in.",
  "metrics.staff-activity.check_outs": "Guests they checked out.",
  "metrics.staff-activity.payments": "Payments they took.",
  "metrics.staff-activity.money": "Money they took, less refunds.",
  "metrics.staff-activity.shifts": "Days they were picked as on duty.",
  "metrics.staff-activity.__first": "The staff member and their role.",
  "metrics.shifts.tile.days-with-a-receptionist-on-record": "The share of days with a receptionist picked as on duty.",
  "metrics.shifts.tile.branches-covered-every-day": "Branches with a receptionist on record every day.",
  "metrics.shifts.tile.branch-days-with-nobody-on-record": "Days at a branch with no receptionist picked.",
  "metrics.shifts.days": "Days counted.",
  "metrics.shifts.reception": "Days with a receptionist on record.",
  "metrics.shifts.missing": "Days without one, and which.",
  "metrics.shifts.waitron": "Days with a waitron on record, where the branch has waitrons.",
  "metrics.alerts.tile.open-alerts": "Every branch's open alerts.",
  "metrics.alerts.tile.unpaid-by-guests-who-left": "Balances guests left owing.",
  "metrics.alerts.tile.credit-to-return": "Credit held for guests who left.",
  "metrics.alerts.missed": "Paid bookings past their arrival day with no check-in.",
  "metrics.alerts.overdue": "Guests past their check-out.",
  "metrics.alerts.unpaid": "Guests who left owing, and how much.",
  "metrics.alerts.unconfirmed": "Website bookings awaiting payment.",
  "metrics.alerts.credits": "Credit held for guests who left, and how much.",
  "metrics.alerts.total": "All open alerts.",
  "metrics.adoption.tile.branches-using-the-pms-every-day": "Branches where someone did something every day.",
  "metrics.adoption.tile.staff-who-used-it": "Branch staff with at least one action.",
  "metrics.adoption.tile.branches-with-nothing-recorded": "Branches with no booking, check-in, payment or F&B order.",
  "metrics.adoption.days": "Days someone did something.",
  "metrics.adoption.staff": "Staff with at least one action.",
  "metrics.adoption.bookings": "Bookings recorded.",
  "metrics.adoption.check_ins": "Check-ins.",
  "metrics.adoption.payments": "Payments.",
  "metrics.adoption.actions": "Everything recorded, of every kind.",
  "metrics.adoption.last": "The latest thing recorded.",
  // ---- Critical
  "critical.ooo": "Every room out of order at every branch, the longest first. The list updates by itself.",
  "critical.col.room": "The room number.",
  "critical.col.branch": "The branch it is at.",
  "critical.col.roomType": "Its room type.",
  "critical.col.since": "When it was set out of order.",
  "critical.col.for": "How long it has been out of order.",
  "critical.col.setBy": "Who set it out of order.",
  // ---- Decision Support
  "decisionSupport.ooo": "Out-of-order rooms ranked by the bookings each may have cost, with what to fix first.",
  "decisionSupport.suggested": "The rooms to fix first: those whose room type sold out while they were out.",
  "decisionSupport.byBranch": "Rooms out of order and their potential loss, branch by branch.",
  "decisionSupport.byType": "Rooms out of order and their potential loss, by room type.",
  "decisionSupport.col.branch": "The branch.",
  "decisionSupport.col.roomType": "The room type, and its branch.",
  "decisionSupport.col.soldOut": "Nights the room type sold every room it had for sale while a room was out.",
  "decisionSupport.col.loss": "Bookings they may have cost: the low end one room per sold-out night, the high end every room out.",
  "decisionSupport.ranked": "Every room out of order, the costliest first.",
  "decisionSupport.col.room": "The room number, with its rank.",
  "decisionSupport.col.price": "The room type's standard price a night.",
  "decisionSupport.col.roomSoldOut": "Sold-out nights, of the nights this room has been out.",
  "decisionSupport.col.roomLoss": "What this room may have cost: its price times its sold-out nights.",
  // ---- Staff Accounts
  "staffAccounts.branch": "Whose staff to list: a branch's, or Head Office's own.",
  "staffAccounts.showDeactivated": "Also lists accounts that can no longer sign in.",
  "staffAccounts.col.username": "The name they sign in with, shown on shifts, reports and the audit trail.",
  "staffAccounts.col.role": "What they can open in the PMS.",
  "staffAccounts.col.status": "Active: can sign in. Inactive: deactivated.",
  "staffAccounts.col.lastLogin": "When they last signed in.",
  "staffAccounts.col.actions": "Rename, Change Role, Reset Password, Transfer to another branch, Deactivate or Reactivate. Each asks you to confirm.",
  "staffAccounts.username": "First name, then last name, e.g. Ada Okafor.",
  "staffAccounts.role": "What they can open in the PMS.",
  "staffAccounts.password": "At least 8 characters. Give it to them privately.",
  "staffAccounts.passwordAgain": "The same password again, to catch a typo.",
  "staffAccounts.newUsername": "The name they will sign in with from now on.",
  "staffAccounts.newRole": "What they will be able to open.",
  "staffAccounts.newPassword": "At least 8 characters. Their old one stops working.",
  "staffAccounts.newBranch": "Where the account moves. Role, username and password stay the same.",
  // ---- Accounting
  "accounting.page": "The accountant's page: check and sign off the branch's books.",
  "accounting.dayClose": "Each business day (6am to 6am), signed off once you have checked it - a record that it was checked. Ten days a page, newest first.",
  "accounting.days.col.day": "The business day: 6am that day to 6am the next.",
  "accounting.days.col.audit": "Whether that night's audit has run. A day can only be signed off once it has.",
  "accounting.days.col.collected": "Money taken that day, less refunds: the Analysis report's Net Total for the day.",
  "accounting.days.col.charged": "Everything charged that day, to guests and non-guests.",
  "accounting.days.col.status": "Open: not signed off yet. Signed off: checked, and nothing has changed since. Changed after sign-off: something was posted into it later - check it and sign it off again.",
  "accounting.days.col.actions": "Open a day to see its figures and sign it off.",
  "accounting.day.changed": "This day's figures no longer match what was signed off: what moved, and what was posted into it since. Usually a night audit run late, a guest's last night charged at check-out, or a reservation's deposit applied when the booking was confirmed (it keeps the day it was taken).",
  "accounting.day.diff.figure": "The figure that moved.",
  "accounting.day.diff.then": "What it was when the day was signed off.",
  "accounting.day.diff.now": "What it is now.",
  "accounting.day.diff.difference": "Now minus at sign-off.",
  "accounting.day.late": "Charges and payments dated into this day but posted after it was signed off: what, on whose folio, by whom and when.",
  "accounting.day.money": "Payments, non-guest sales, refunds and credit refunds by method, as the Analysis report counts them.",
  "accounting.day.credit": "Money paid ahead for bookings that day (reservation credit), by method. Not part of Collected until it is used.",
  "accounting.day.charges": "Everything charged that day, by type: guest folios by the date charged, non-guest sales by when they were rung up.",
  "accounting.day.audit": "The night audit for this day: the rooms it charged and what it posted.",
  "accounting.day.signedOff": "Who signed this day off, and when.",
  "accounting.day.history": "This day's earlier sign-offs, each replaced when the day changed and was signed off again.",
  "accounting.day.note": "Anything worth recording with the sign-off; kept with it and shown in the Audit Trail. Needed when signing a changed day off again: say what you checked.",
  "accounting.cashUp": "Per person, for one business day: what the system expects them to hold beside what they counted. Verify each once you have checked it.",
  "accounting.cashUp.day": "The business day to check: 6am that day to 6am the next. Yesterday by default.",
  "accounting.cashUp.col.method": "How the money was taken.",
  "accounting.cashUp.col.expected": "What they should hold: money they took and reservation credit, less refunds and credit refunds they paid out and their paid-outs.",
  "accounting.cashUp.col.declared": "What they counted and submitted, without seeing what was expected.",
  "accounting.cashUp.col.difference": "Counted minus expected. Red when they don't match: short below zero, over above.",
  "accounting.cashUp.paidOuts": "Cash they paid out of their drawer for small expenses that day. Already taken off what they are expected to hold.",
  "accounting.cashUp.verified": "Who verified this cash-up, and when. It can't be changed after.",
  "accounting.cashUp.reviewNote": "Anything worth recording with the verification - why a difference is fine, what was counted again. Shown in the Audit Trail.",
  "accounting.exceptions": "Every way money was given back or taken off - refunds, credit refunds, adjustments, corrections, rates below standard, rooms made complementary, free food and drink - line by line. Mark each OK, or flag it for the manager.",
  "accounting.exceptions.from": "The first business day to list (6am that day).",
  "accounting.exceptions.to": "The last business day to list (until 6am the next day). Up to 31 days at a time.",
  "accounting.exceptions.show": "Which lines to show: those not reviewed yet (the default), those flagged for the manager, those marked OK, or all of them.",
  "accounting.exceptions.totals": "Every line in these days, by section, and what it gave away: money paid back, taken off bills, below the standard rate, or food and drink at menu price. A correction that added to a bill gives nothing away.",
  "accounting.exceptions.note": "Why it is fine, or what the manager should look at. Shown with the review, to the manager on Alerts, and in the Audit Trail.",
  "accounting.exceptions.col.when": "The business day it belongs to, and the time it was recorded. A rate below standard is on the stay's check-in day.",
  "accounting.exceptions.col.what": "What kind of exception it is, and its details.",
  "accounting.exceptions.col.amount": "Money paid back, taken off a bill (negative), the discount below the standard rate, or free food and drink at menu price. A room made complementary has no amount: the night audit charges nothing for it while it stays complementary.",
  "accounting.exceptions.col.by": "Who did it: paid the money back, posted the line, checked the guest in at that rate, or marked the room.",
  "accounting.exceptions.col.guest": "The guest or bill it was for, and its folio, receipt or booking reference.",
  "accounting.exceptions.col.reason": "The note typed with it, if any.",
  "accounting.exceptions.col.review": "Not reviewed, OK, or flagged for the manager - with who reviewed it and their note.",
  "accounting.receivables": "What is owed to the branch - by guests in the house, by guests who left owing, and on open non-guest bills - with your follow-up notes on each.",
  "accounting.receivables.totals": "What each ledger is owed in all. In house can be negative: guests there hold more credit than they owe.",
  "accounting.receivables.city": "Guests who left owing (the city ledger), and no-shows charged a fee, by how long ago they left. Money still due from a booking site isn't the guest's and isn't counted.",
  "accounting.receivables.house": "Guests in the house now and what each owes (the guest ledger): the folio's balance less anything a booking site is still to pay.",
  "accounting.receivables.nonGuest": "Open non-guest bills (F&B and laundry) with money still owed, by how long they have been open.",
  "accounting.receivables.note": "What was done to collect it - a call, a promise, a reminder sent. Kept with today's date and your name.",
  "accounting.receivables.notes": "Every follow-up note on this bill, newest first.",
  "accounting.receivables.col.guest": "The guest, their folio number and phone.",
  "accounting.receivables.col.left": "The business day they left (a no-show: the night they were booked for), and how long ago. Red after 30 days.",
  "accounting.receivables.col.owes": "What is still owed.",
  "accounting.receivables.col.owesNow": "What the guest owes now. Green: they hold credit instead.",
  "accounting.receivables.col.room": "The room or rooms they are in.",
  "accounting.receivables.col.dueOut": "The day they are booked to leave.",
  "accounting.receivables.col.lastPayment": "The last money paid on this bill, how, and when.",
  "accounting.receivables.col.note": "The latest follow-up note on this bill, who wrote it and when.",
  "accounting.receivables.col.actions": "Notes: add or read follow-up notes. Statement: a printable statement for the guest. Folio: open the guest's folio.",
  "accounting.receivables.col.bill": "Who the non-guest bill is for (if a name was taken), its number, F&B or laundry, and phone.",
  "accounting.receivables.col.opened": "The business day the bill was opened, and how long ago. Red after 30 days.",
  "accounting.deposits": "Reservation credit the branch holds - paid ahead for a booking, or an overpayment kept on a stay - that hasn't been spent or paid back, by where its stay is.",
  "accounting.deposits.totals": "Held: all of it. To chase: the part on stays that have ended - guests who left, no-shows, cancelled bookings - which nobody is coming back to use.",
  "accounting.deposits.group.arriving": "Credit on bookings still to arrive. It goes on their bill when they check in.",
  "accounting.deposits.group.in_house": "Credit on guests in the house, waiting to pay their charges.",
  "accounting.deposits.group.departed": "Credit left on stays that have checked out: refund it, or have the front desk move it to a stay the guest has now.",
  "accounting.deposits.group.no_show": "Credit on bookings marked no-show.",
  "accounting.deposits.group.cancelled": "Credit on cancelled bookings.",
  "accounting.deposits.group.other": "Credit not tied to any booking.",
  "accounting.deposits.col.guest": "The guest, their booking reference and phone.",
  "accounting.deposits.col.taken": "The business day the money was taken, how long ago, and who took it.",
  "accounting.deposits.col.waiting": "How long it has waited since the stay ended: since they left, the night they were booked for (no-show), or the booking was cancelled. Red after 30 days.",
  "accounting.deposits.col.receipt": "The credit's reference and the paper receipt number typed with it.",
  "accounting.deposits.col.credit": "What is left to spend or pay back, how it was paid, and whether it was paid ahead or is an overpayment. Part may already have gone to charges.",
  "accounting.deposits.col.actions": "Refund: pay it back to the guest, recorded under your name. Folio: open the stay's folio.",

  // ---- Cash-Up
  "cashUp.page": "Count what you hold and submit it. You won't see what the system expects; the accountant compares the two.",
  "cashUp.day": "Today, or yesterday if your shift ran past 6am. A business day runs 6am to 6am.",
  "cashUp.declaration": "What you hold for this business day, by method. You can change it until the accountant verifies it.",
  "cashUp.method.cash": "Cash in your drawer.",
  "cashUp.method.card": "Card payments you took.",
  "cashUp.method.transfer": "Bank transfers you took.",
  "cashUp.method.pos": "POS payments you took (the terminal's total).",
  "cashUp.method.online": "Online payments you took.",
  "cashUp.note": "Anything the accountant should know about your count.",
  "cashUp.total": "Everything you counted, all methods together.",
  "cashUp.paidOuts": "Cash paid out of your drawer for a small expense. Recorded on the day it happens.",
  "cashUp.paidOut.amount": "How much cash left the drawer.",
  "cashUp.paidOut.category": "What the money was spent on.",
  "cashUp.paidOut.description": "What it was spent on, in a few words.",
  "cashUp.paidOut.voucher": "The number on the voucher or receipt, if there is one.",
  "cashUp.paidOut.note": "Anything else worth knowing about it.",
  "cashUp.paidOut.col.what": "What the money was spent on.",
  "cashUp.paidOut.col.amount": "How much cash left the drawer. Struck through when cancelled.",
  "cashUp.paidOut.col.voucher": "The voucher or receipt number.",
  "cashUp.paidOut.col.time": "When it was recorded.",
  "cashUp.paidOut.col.actions": "A paid-out can be cancelled the same day, until your cash-up is verified.",
  "cashUp.paidOutTotal": "All of today's paid-outs that aren't cancelled.",
};

export const tipText = (id) => TIPS[id] || null;
